# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ safenotes ]
  #pull_request:
   # branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
 # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout workspace
      - uses: actions/checkout@v2        
        
      # Run unit tests
     # - name: run unit tests
     #   run: bash ./gradlew test --stacktrace

      # Build apk
     # - name: build apk
     #   run: bash ./gradlew assembleDebug --stacktrace
        
      # Upload apk
   #   - name: upload apk artifact
    #    uses: actions/upload-artifact@v2.2.0 
