package com.vikas.mobile.mysafenotes.data.entity

import androidx.room.*

// ------------------ note_table ------------------------------------------------------
// id (autogenerated) | category_id (foreignKey) | content
//--------------------------------------------------------------------------------------
//        1           |            1             | ICICI BANK, account number: xxxx, pin: xxxx
//        2           |            1             | HDFC BANK, account number: xxxx, pin: xxxx
//        3           |            2             | I should wake up 6:00 am early in morning
//        4           |            2             | Better I should start meditation
//        5           |            3             | My school friends: x, y, z, z1
//        6           |            3             | My office friends: p, q, r

@Entity(
        tableName = "note_table", indices = [Index(value = ["category_id"])],
        foreignKeys = [
            ForeignKey(entity = Category::class, parentColumns = ["id"], childColumns = ["category_id"])
        ])
data class Note (
        @ColumnInfo(name = "category_id")
        var categoryId: Long,

        @ColumnInfo(name = "content")
        var noteContent: MaskedData
) {
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "id")
    var id: Long = 0
}